openapi: "3.0.0"
info:
  version: 1.0.0
  title: Role API
paths:
  /role:
    post:
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеРоли:
                  type: string
                Описание:
                  type: string
      responses:
        '201':
          description: Created
    get:
      summary: Get all roles
      responses:
        '200':
          description: A list of roles
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDроли:
                      type: integer
                    НазваниеРоли:
                      type: string
                    Описание:
                      type: string
  /role/{id}:
    put:
      summary: Update a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеРоли:
                  type: string
                Описание:
                  type: string
      responses:
        '204':
          description: No Content
    get:
      summary: Get a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A role
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDроли:
                    type: integer
                  НазваниеРоли:
                    type: string
                  Описание:
                    type: string
    delete:
      summary: Delete a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
