openapi: "3.0.0"
info:
  version: 1.0.0
  title: Управление задачами игровой студии
servers:
  - url: http://localhost:8000
tags:
- name: Пользователи
- name: Приоритеты
- name: Проекты
- name: Роли
- name: Назначения
- name: Статусы
- name: Задачи
paths:
  /user:
    post:
      tags:
      - Пользователи
      summary: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ИмяПользователя:
                  type: string
                АдресЭлектроннойПочты:
                  type: string
                IDpоли:
                  type: integer
      responses:
        '201':
          description: User created
    get:
      tags:
      - Пользователи
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: An array of users
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ИмяПользователя:
                      type: string
                    АдресЭлектроннойПочты:
                      type: string
                    IDpоли:
                      type: integer
  /user/{id}:
    get:
      tags:
      - Пользователи
      summary: Get a user by ID
      operationId: fetchUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A user object
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  ИмяПользователя:
                    type: string
                  АдресЭлектроннойПочты:
                    type: string
                  IDpоли:
                    type: integer
    put:
      tags:
      - Пользователи
      summary: Update a user by ID
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ИмяПользователя:
                  type: string
                АдресЭлектроннойПочты:
                  type: string
                IDpоли:
                  type: integer
      responses:
        '204':
          description: User updated
    delete:
      tags:
      - Пользователи
      summary: Delete a user by ID
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: User deleted
  /priority:
    post:
      tags:
      - Приоритеты
      summary: Create a new priority
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеПриоритета:
                  type: string
      responses:
        '201':
          description: Created
    get:
      tags:
      - Приоритеты
      summary: Get all priorities
      responses:
        '200':
          description: A list of priorities
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDприоритета:
                      type: integer
                    НазваниеПриоритета:
                      type: string
  /priority/{id}:
    put:
      tags:
      - Приоритеты
      summary: Update a priority
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеПриоритета:
                  type: string
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Приоритеты
      summary: Get a priority
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A priority
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDприоритета:
                    type: integer
                  НазваниеПриоритета:
                    type: string
    delete:
      tags:
      - Приоритеты
      summary: Delete a priority
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
  /project:
    post:
      tags:
      - Проекты
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеПроекта:
                  type: string
                ДатаНачала:
                  type: string
                ОжидаемаяДатаЗавершения:
                  type: string
                IDстатуса:
                  type: integer
      responses:
        '201':
          description: Created
    get:
      tags:
      - Проекты
      summary: Get all projects
      responses:
        '200':
          description: A list of projects
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDпроекта:
                      type: integer
                    НазваниеПроекта:
                      type: string
                    ДатаНачала:
                      type: string
                    ОжидаемаяДатаЗавершения:
                      type: string
                    IDстатуса:
                      type: integer
  /project/{id}:
    put:
      tags:
      - Проекты
      summary: Update a project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеПроекта:
                  type: string
                ДатаНачала:
                  type: string
                ОжидаемаяДатаЗавершения:
                  type: string
                IDстатуса:
                  type: integer
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Проекты
      summary: Get a project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A project
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDпроекта:
                    type: integer
                  НазваниеПроекта:
                    type: string
                  ДатаНачала:
                    type: string
                  ОжидаемаяДатаЗавершения:
                    type: string
                  IDстатуса:
                    type: integer
    delete:
      tags:
      - Проекты
      summary: Delete a project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
  /role:
    post:
      tags:
      - Роли
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеРоли:
                  type: string
                Описание:
                  type: string
      responses:
        '201':
          description: Created
    get:
      tags:
      - Роли
      summary: Get all roles
      responses:
        '200':
          description: A list of roles
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDроли:
                      type: integer
                    НазваниеРоли:
                      type: string
                    Описание:
                      type: string
  /role/{id}:
    put:
      tags:
      - Роли
      summary: Update a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеРоли:
                  type: string
                Описание:
                  type: string
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Роли
      summary: Get a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A role
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDроли:
                    type: integer
                  НазваниеРоли:
                    type: string
                  Описание:
                    type: string
    delete:
      tags:
      - Роли
      summary: Delete a role
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
  /assignment:
    post:
      tags:
      - Назначения
      summary: Create a new assignment
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                IDпользователя:
                  type: integer
                IDзадачи:
                  type: integer
                ДатаНазначения:
                  type: string
      responses:
        '201':
          description: Created
    get:
      tags:
      - Назначения
      summary: Get all assignments
      responses:
        '200':
          description: A list of assignments
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDназначения:
                      type: integer
                    IDпользователя:
                      type: integer
                    IDзадачи:
                      type: integer
                    ДатаНазначения:
                      type: string
  /assignment/{id}:
    put:
      tags:
      - Назначения
      summary: Update an assignment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                IDпользователя:
                  type: integer
                IDзадачи:
                  type: integer
                ДатаНазначения:
                  type: string
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Назначения
      summary: Get an assignment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: An assignment
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDназначения:
                    type: integer
                  IDпользователя:
                    type: integer
                  IDзадачи:
                    type: integer
                  ДатаНазначения:
                    type: string
    delete:
      tags:
      - Назначения
      summary: Delete an assignment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
  /status:
    post:
      tags:
      - Статусы
      summary: Create a new status
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеСтатуса:
                  type: string
      responses:
        '201':
          description: Created
    get:
      tags:
      - Статусы
      summary: Get all statuses
      responses:
        '200':
          description: A list of statuses
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDстатуса:
                      type: integer
                    НазваниеСтатуса:
                      type: string
  /status/{id}:
    put:
      tags:
      - Статусы
      summary: Update a status
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                НазваниеСтатуса:
                  type: string
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Статусы
      summary: Get a status
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A status
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDстатуса:
                    type: integer
                  НазваниеСтатуса:
                    type: string
    delete:
      tags:
      - Статусы
      summary: Delete a status
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
  /task:
    post:
      tags:
      - Задачи
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                IDпроекта:
                  type: integer
                НазваниеЗадачи:
                  type: string
                ОписаниеЗадачи:
                  type: string
                ДатаНачала:
                  type: string
                ДатаОкончания:
                  type: string
                IDстатуса:
                  type: integer
                IDприоритета:
                  type: integer
      responses:
        '201':
          description: Created
    get:
      tags:
      - Задачи
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/x-www-form-urlencoded:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDзадачи:
                      type: integer
                    IDпроекта:
                      type: integer
                    НазваниеЗадачи:
                      type: string
                    ОписаниеЗадачи:
                      type: string
                    ДатаНачала:
                      type: string
                    ДатаОкончания:
                      type: string
                    IDстатуса:
                      type: integer
                    IDприоритета:
                      type: integer
  /task/{id}:
    put:
      tags:
      - Задачи
      summary: Update a task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                IDпроекта:
                  type: integer
                НазваниеЗадачи:
                  type: string
                ОписаниеЗадачи:
                  type: string
                ДатаНачала:
                  type: string
                ДатаОкончания:
                  type: string
                IDстатуса:
                  type: integer
                IDприоритета:
                  type: integer
      responses:
        '204':
          description: No Content
    get:
      tags:
      - Задачи
      summary: Get a task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: A task
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  IDзадачи:
                    type: integer
                  IDпроекта:
                    type: integer
                  НазваниеЗадачи:
                    type: string
                  ОписаниеЗадачи:
                    type: string
                  ДатаНачала:
                    type: string
                  ДатаОкончания:
                    type: string
                  IDстатуса:
                    type: integer
                  IDприоритета:
                    type: integer
    delete:
      tags:
      - Задачи
      summary: Delete a task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: No Content
